server:
  port: ${SERVER_PORT}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: Slick
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: headers
  task:
    scheduling:
      pool:
        size: 4

logging:
  level:
    toy.slick.feign: debug
    org.jooq.tools.LoggerListener: debug
    org.jooq.Constants: off

telegram:
  bot:
    slick:
      token: ${BOT_SLICK_TOKEN}
  chat:
    slick:
      dev:
        id: ${CHAT_SLICK_DEV_ID}
      us:
        id: ${CHAT_SLICK_US_ID}
      kr:
        id: ${CHAT_SLICK_KR_ID}

controller:
  key: ${CONTROLLER_KEY}

management:
  endpoints:
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: health
    access:
      default: read_only
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
      access: read_only
