logging:
  level:
    root: warn
    sql: warn
    org.jooq.Constants: off
    toy.slick.feign: warn
    toy.slick: info

spring:
  datasource:
    hikari:
      minimum-idle: 3
      maximum-pool-size: 5